FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY index.html ./
COPY tsconfig.json vite.config.ts tailwind.config.ts postcss.config.js ./
COPY src ./src

EXPOSE 5173
CMD ["npm", "run", "dev"]
